# Generated by Django 5.0.1 on 2025-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clients', models.CharField(max_length=32, null=True)),
                ('prenom_clients', models.CharField(max_length=32, null=True)),
                ('numero_clients', models.CharField(max_length=32, null=True)),
                ('adress_clients', models.CharField(max_length=32, null=True)),
                ('email_clients', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
