# Generated by Django 5.0.1 on 2025-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listesCommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listes_listesCommandes', models.CharField(max_length=32, null=True)),
                ('total_listesCommandes', models.DecimalField(decimal_places=3, max_digits=10)),
                ('statue_listesCommandes', models.IntegerField(default=1)),
            ],
        ),
    ]
