# Generated by Django 5.0.1 on 2025-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nouritures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_ntr', models.CharField(max_length=32, null=True)),
                ('nom_ntr', models.CharField(max_length=32, null=True)),
                ('ingredient_ntr', models.CharField(max_length=32, null=True)),
                ('prix_ntr', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
